// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/route/rule
// Commit: 877e7a8
// Generated at: 2025-11-23T20:37:59Z

package types

// Config represents the main sing-box configuration
// This is a simplified version without custom unmarshalling
type Config struct {
	Log          *LogOptions          `json:"log,omitempty"`
	DNS          *RawDNSOptions       `json:"dns,omitempty"`
	NTP          *NTPOptions          `json:"ntp,omitempty"`
	Inbounds     []interface{}        `json:"inbounds,omitempty"`
	Outbounds    []interface{}        `json:"outbounds,omitempty"`
	Route        *RouteOptions        `json:"route,omitempty"`
	Experimental *ExperimentalOptions `json:"experimental,omitempty"`
}

type LogOptions struct {
	Disabled  bool   `json:"disabled,omitempty"`
	Level     string `json:"level,omitempty"`
	Output    string `json:"output,omitempty"`
	Timestamp bool   `json:"timestamp,omitempty"`
}

type StubOptions struct {
}
