// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/route/rule
// Commit: 877e7a8
// Generated at: 2025-11-23T20:44:59Z

package types

type RawDNSOptions struct {
	Servers        []interface{} `json:"servers,omitempty"`
	Rules          []interface{} `json:"rules,omitempty"`
	Final          string        `json:"final,omitempty"`
	ReverseMapping bool          `json:"reverse_mapping,omitempty"`
}

type LegacyDNSOptions struct {
	FakeIP *LegacyDNSFakeIPOptions `json:"fakeip,omitempty"`
}

type DNSOptions struct {
}

type DNSClientOptions struct {
	Strategy         string  `json:"strategy,omitempty"`
	DisableCache     bool    `json:"disable_cache,omitempty"`
	DisableExpire    bool    `json:"disable_expire,omitempty"`
	IndependentCache bool    `json:"independent_cache,omitempty"`
	CacheCapacity    uint32  `json:"cache_capacity,omitempty"`
	ClientSubnet     *string `json:"client_subnet,omitempty"`
}

type LegacyDNSFakeIPOptions struct {
	Enabled    bool    `json:"enabled,omitempty"`
	Inet4Range *string `json:"inet4_range,omitempty"`
	Inet6Range *string `json:"inet6_range,omitempty"`
}

type DNSTransportOptionsRegistry struct {
}

type DNSServerAddressOptions struct {
	Server     string `json:"server"`
	ServerPort uint16 `json:"server_port,omitempty"`
}

type LegacyDNSServerOptions struct {
	Address              string  `json:"address"`
	AddressResolver      string  `json:"address_resolver,omitempty"`
	AddressStrategy      string  `json:"address_strategy,omitempty"`
	AddressFallbackDelay uint32  `json:"address_fallback_delay,omitempty"`
	Strategy             string  `json:"strategy,omitempty"`
	Detour               string  `json:"detour,omitempty"`
	ClientSubnet         *string `json:"client_subnet,omitempty"`
}

type HostsDNSServerOptions struct {
	Path       []string                `json:"path,omitempty"`
	Predefined *map[string]interface{} `json:"predefined,omitempty"`
}

type RawLocalDNSServerOptions struct {
}

type LocalDNSServerOptions struct {
	PreferGo bool `json:"prefer_go,omitempty"`
}

type RemoteDNSServerOptions struct {
}

type RemoteTLSDNSServerOptions struct {
}

type RemoteHTTPSDNSServerOptions struct {
	Path    string            `json:"path,omitempty"`
	Method  string            `json:"method,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
}

type FakeIPDNSServerOptions struct {
	Inet4Range *string `json:"inet4_range,omitempty"`
	Inet6Range *string `json:"inet6_range,omitempty"`
}

type DHCPDNSServerOptions struct {
	Interface string `json:"interface,omitempty"`
}
