// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/route/rule
// Commit: 877e7a8
// Generated at: 2025-11-23T20:44:59Z

package types

type InboundOptionsRegistry struct {
}

// Deprecated: Use rule action instead
type InboundOptions struct {
	SniffEnabled              bool   `json:"sniff,omitempty"`
	SniffOverrideDestination  bool   `json:"sniff_override_destination,omitempty"`
	SniffTimeout              uint32 `json:"sniff_timeout,omitempty"`
	DomainStrategy            string `json:"domain_strategy,omitempty"`
	UDPDisableDomainUnmapping bool   `json:"udp_disable_domain_unmapping,omitempty"`
	Detour                    string `json:"detour,omitempty"`
}

type ListenOptions struct {
	Listen               *string `json:"listen,omitempty"`
	ListenPort           uint16  `json:"listen_port,omitempty"`
	BindInterface        string  `json:"bind_interface,omitempty"`
	RoutingMark          uint32  `json:"routing_mark,omitempty"`
	ReuseAddr            bool    `json:"reuse_addr,omitempty"`
	NetNs                string  `json:"netns,omitempty"`
	TCPKeepAlive         uint32  `json:"tcp_keep_alive,omitempty"`
	TCPKeepAliveInterval uint32  `json:"tcp_keep_alive_interval,omitempty"`
	TCPFastOpen          bool    `json:"tcp_fast_open,omitempty"`
	TCPMultiPath         bool    `json:"tcp_multi_path,omitempty"`
	UDPFragment          *bool   `json:"udp_fragment,omitempty"`
	UDPTimeout           uint32  `json:"udp_timeout,omitempty"`
	// Deprecated: removed
	ProxyProtocol bool `json:"proxy_protocol,omitempty"`
	// Deprecated: removed
	ProxyProtocolAcceptNoHeader bool `json:"proxy_protocol_accept_no_header,omitempty"`
}

type ListenOptionsWrapper struct {
}
