// Code generated by singbox-web-config generator. DO NOT EDIT.

package types

import "time"

// Metadata contains information about the code generation
var Metadata = struct {
	Timestamp        time.Time
	SingBoxCommit    string
	SingBoxBranch    string
	GeneratorVersion string
	TypesGenerated   int
}{
	Timestamp:        time.Unix(1763930699, 0),
	SingBoxCommit:    "877e7a8",
	SingBoxBranch:    "dev-next",
	GeneratorVersion: "0.1.0",
	TypesGenerated:   55,
}
