// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/route/rule
// Commit: 877e7a8
// Generated at: 2025-11-23T20:44:59Z

package types

type NTPOptions struct {
	Enabled       bool   `json:"enabled,omitempty"`
	Interval      uint32 `json:"interval,omitempty"`
	WriteToSystem bool   `json:"write_to_system,omitempty"`
}
