// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/option
// Commit: 877e7a8
// Generated at: 2025-11-24T00:00:00Z

package types

// OutboundOptionsRegistry is a registry for all outbound types
type OutboundOptionsRegistry struct{}

// DialerOptionsWrapper wraps dialer options
type DialerOptionsWrapper struct{}

// DialerOptions contains common dial configuration for outbounds
type DialerOptions struct {
	Detour              string       `json:"detour,omitempty"`
	BindInterface       string       `json:"bind_interface,omitempty"`
	Inet4BindAddress    *string      `json:"inet4_bind_address,omitempty"`
	Inet6BindAddress    *string      `json:"inet6_bind_address,omitempty"`
	ProtectPath         string       `json:"protect_path,omitempty"`
	RoutingMark         uint32       `json:"routing_mark,omitempty"`
	ReuseAddr           bool         `json:"reuse_addr,omitempty"`
	NetNs               string       `json:"netns,omitempty"`
	ConnectTimeout      uint32       `json:"connect_timeout,omitempty"`
	TCPFastOpen         bool         `json:"tcp_fast_open,omitempty"`
	TCPMultiPath        bool         `json:"tcp_multi_path,omitempty"`
	UDPFragment         *bool        `json:"udp_fragment,omitempty"`
	DomainResolver      *interface{} `json:"domain_resolver,omitempty"`
	NetworkStrategy     *string      `json:"network_strategy,omitempty"`
	NetworkType         []string     `json:"network_type,omitempty"`
	FallbackNetworkType []string     `json:"fallback_network_type,omitempty"`
	FallbackDelay       uint32       `json:"fallback_delay,omitempty"`
	// Deprecated: migrated to domain resolver
	DomainStrategy string `json:"domain_strategy,omitempty"`
}

// ServerOptionsWrapper wraps server options
type ServerOptionsWrapper struct{}

// ServerOptions contains server connection details
type ServerOptions struct {
	Server     string `json:"server"`
	ServerPort uint16 `json:"server_port"`
}

// TLSOptions contains TLS configuration
type TLSOptions struct {
	Enabled         *bool    `json:"enabled,omitempty"`
	DisableSNI      bool     `json:"disable_sni,omitempty"`
	ServerName      string   `json:"server_name,omitempty"`
	Insecure        bool     `json:"insecure,omitempty"`
	ALPN            []string `json:"alpn,omitempty"`
	MinVersion      string   `json:"min_version,omitempty"`
	MaxVersion      string   `json:"max_version,omitempty"`
	CipherSuites    []string `json:"cipher_suites,omitempty"`
	Certificate     string   `json:"certificate,omitempty"`
	CertificatePath string   `json:"certificate_path,omitempty"`
	ECH             *ECHOptions `json:"ech,omitempty"`
	UTLS            *UTLSOptions `json:"utls,omitempty"`
	Reality         *RealityOptions `json:"reality,omitempty"`
}

// ECHOptions contains ECH configuration
type ECHOptions struct {
	Enabled        bool     `json:"enabled,omitempty"`
	PQSignatureSchemesEnabled bool `json:"pq_signature_schemes_enabled,omitempty"`
	DynamicRecordSizingDisabled bool `json:"dynamic_record_sizing_disabled,omitempty"`
	Config         []string `json:"config,omitempty"`
}

// UTLSOptions contains UTLS configuration
type UTLSOptions struct {
	Enabled     bool   `json:"enabled,omitempty"`
	Fingerprint string `json:"fingerprint,omitempty"`
}

// RealityOptions contains Reality TLS configuration
type RealityOptions struct {
	Enabled   bool   `json:"enabled,omitempty"`
	PublicKey string `json:"public_key,omitempty"`
	ShortID   string `json:"short_id,omitempty"`
}

// MultiplexOptions contains multiplex configuration
type MultiplexOptions struct {
	Enabled        bool   `json:"enabled,omitempty"`
	Protocol       string `json:"protocol,omitempty"`
	MaxConnections int    `json:"max_connections,omitempty"`
	MinStreams     int    `json:"min_streams,omitempty"`
	MaxStreams     int    `json:"max_streams,omitempty"`
	Padding        bool   `json:"padding,omitempty"`
	Brutal         *BrutalOptions `json:"brutal,omitempty"`
}

// BrutalOptions contains brutal congestion control options
type BrutalOptions struct {
	Enabled  bool   `json:"enabled,omitempty"`
	UpMbps   uint32 `json:"up_mbps,omitempty"`
	DownMbps uint32 `json:"down_mbps,omitempty"`
}

// V2RayTransportOptions contains V2Ray transport options
type V2RayTransportOptions struct {
	Type        string                     `json:"type,omitempty"`
	HTTPOptions *V2RayHTTPOptions          `json:"-"`
	WebsocketOptions *V2RayWebsocketOptions `json:"-"`
	QUICOptions *V2RayQUICOptions          `json:"-"`
	GRPCOptions *V2RayGRPCOptions          `json:"-"`
	HTTPUpgradeOptions *V2RayHTTPUpgradeOptions `json:"-"`
}

// V2RayHTTPOptions contains HTTP transport options
type V2RayHTTPOptions struct {
	Host        []string          `json:"host,omitempty"`
	Path        string            `json:"path,omitempty"`
	Method      string            `json:"method,omitempty"`
	Headers     map[string]string `json:"headers,omitempty"`
	IdleTimeout uint32            `json:"idle_timeout,omitempty"`
	PingTimeout uint32            `json:"ping_timeout,omitempty"`
}

// V2RayWebsocketOptions contains WebSocket transport options
type V2RayWebsocketOptions struct {
	Path                string            `json:"path,omitempty"`
	Headers             map[string]string `json:"headers,omitempty"`
	MaxEarlyData        uint32            `json:"max_early_data,omitempty"`
	EarlyDataHeaderName string            `json:"early_data_header_name,omitempty"`
}

// V2RayQUICOptions contains QUIC transport options
type V2RayQUICOptions struct {
	Security string `json:"security,omitempty"`
}

// V2RayGRPCOptions contains gRPC transport options
type V2RayGRPCOptions struct {
	ServiceName         string `json:"service_name,omitempty"`
	IdleTimeout         uint32 `json:"idle_timeout,omitempty"`
	PingTimeout         uint32 `json:"ping_timeout,omitempty"`
	PermitWithoutStream bool   `json:"permit_without_stream,omitempty"`
}

// V2RayHTTPUpgradeOptions contains HTTP upgrade transport options
type V2RayHTTPUpgradeOptions struct {
	Host    string            `json:"host,omitempty"`
	Path    string            `json:"path,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
}

// UDPOverTCPOptions contains UDP over TCP options
type UDPOverTCPOptions struct {
	Enabled bool   `json:"enabled,omitempty"`
	Version uint8  `json:"version,omitempty"`
}

// DirectOutbound represents a direct connection outbound
type DirectOutbound struct {
	Type             string `json:"type"`
	Tag              string `json:"tag"`
	OverrideAddress  string `json:"override_address,omitempty"`
	OverridePort     uint16 `json:"override_port,omitempty"`
	ProxyProtocol    uint8  `json:"proxy_protocol,omitempty"`
	DialerOptions
}

// BlockOutbound represents a block outbound
type BlockOutbound struct {
	Type string `json:"type"`
	Tag  string `json:"tag"`
}

// DNSOutbound represents a DNS outbound
type DNSOutbound struct {
	Type string `json:"type"`
	Tag  string `json:"tag"`
}

// SocksOutbound represents a SOCKS proxy outbound
type SocksOutbound struct {
	Type     string `json:"type"`
	Tag      string `json:"tag"`
	Server   string `json:"server"`
	ServerPort uint16 `json:"server_port"`
	Version  string `json:"version,omitempty"`
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
	Network  string `json:"network,omitempty"`
	UDPOverTCP *UDPOverTCPOptions `json:"udp_over_tcp,omitempty"`
	DialerOptions
}

// HTTPOutbound represents an HTTP proxy outbound
type HTTPOutbound struct {
	Type       string   `json:"type"`
	Tag        string   `json:"tag"`
	Server     string   `json:"server"`
	ServerPort uint16   `json:"server_port"`
	Username   string   `json:"username,omitempty"`
	Password   string   `json:"password,omitempty"`
	TLS        *TLSOptions `json:"tls,omitempty"`
	Path       string   `json:"path,omitempty"`
	Headers    map[string]string `json:"headers,omitempty"`
	DialerOptions
}

// ShadowsocksOutbound represents a Shadowsocks outbound
type ShadowsocksOutbound struct {
	Type       string `json:"type"`
	Tag        string `json:"tag"`
	Server     string `json:"server"`
	ServerPort uint16 `json:"server_port"`
	Method     string `json:"method"`
	Password   string `json:"password"`
	Plugin     string `json:"plugin,omitempty"`
	PluginOpts string `json:"plugin_opts,omitempty"`
	Network    string `json:"network,omitempty"`
	UDPOverTCP *UDPOverTCPOptions `json:"udp_over_tcp,omitempty"`
	Multiplex  *MultiplexOptions  `json:"multiplex,omitempty"`
	DialerOptions
}

// VMessOutbound represents a VMess outbound
type VMessOutbound struct {
	Type            string                 `json:"type"`
	Tag             string                 `json:"tag"`
	Server          string                 `json:"server"`
	ServerPort      uint16                 `json:"server_port"`
	UUID            string                 `json:"uuid"`
	Security        string                 `json:"security,omitempty"`
	AlterId         int                    `json:"alter_id,omitempty"`
	GlobalPadding   bool                   `json:"global_padding,omitempty"`
	AuthenticatedLength bool               `json:"authenticated_length,omitempty"`
	Network         string                 `json:"network,omitempty"`
	TLS             *TLSOptions            `json:"tls,omitempty"`
	PacketEncoding  string                 `json:"packet_encoding,omitempty"`
	Multiplex       *MultiplexOptions      `json:"multiplex,omitempty"`
	Transport       *V2RayTransportOptions `json:"transport,omitempty"`
	DialerOptions
}

// VLESSOutbound represents a VLESS outbound
type VLESSOutbound struct {
	Type           string                 `json:"type"`
	Tag            string                 `json:"tag"`
	Server         string                 `json:"server"`
	ServerPort     uint16                 `json:"server_port"`
	UUID           string                 `json:"uuid"`
	Flow           string                 `json:"flow,omitempty"`
	Network        string                 `json:"network,omitempty"`
	TLS            *TLSOptions            `json:"tls,omitempty"`
	PacketEncoding string                 `json:"packet_encoding,omitempty"`
	Multiplex      *MultiplexOptions      `json:"multiplex,omitempty"`
	Transport      *V2RayTransportOptions `json:"transport,omitempty"`
	DialerOptions
}

// TrojanOutbound represents a Trojan outbound
type TrojanOutbound struct {
	Type       string                 `json:"type"`
	Tag        string                 `json:"tag"`
	Server     string                 `json:"server"`
	ServerPort uint16                 `json:"server_port"`
	Password   string                 `json:"password"`
	Network    string                 `json:"network,omitempty"`
	TLS        *TLSOptions            `json:"tls,omitempty"`
	Multiplex  *MultiplexOptions      `json:"multiplex,omitempty"`
	Transport  *V2RayTransportOptions `json:"transport,omitempty"`
	DialerOptions
}

// WireGuardOutbound represents a WireGuard outbound
type WireGuardOutbound struct {
	Type              string   `json:"type"`
	Tag               string   `json:"tag"`
	Server            string   `json:"server"`
	ServerPort        uint16   `json:"server_port"`
	SystemInterface   bool     `json:"system_interface,omitempty"`
	InterfaceName     string   `json:"interface_name,omitempty"`
	LocalAddress      []string `json:"local_address"`
	PrivateKey        string   `json:"private_key"`
	Peers             []WireGuardPeer `json:"peers"`
	PeerPublicKey     string   `json:"peer_public_key,omitempty"`
	PreSharedKey      string   `json:"pre_shared_key,omitempty"`
	Reserved          []uint8  `json:"reserved,omitempty"`
	Workers           int      `json:"workers,omitempty"`
	MTU               uint32   `json:"mtu,omitempty"`
	Network           string   `json:"network,omitempty"`
	DialerOptions
}

// WireGuardPeer represents a WireGuard peer
type WireGuardPeer struct {
	Server       string   `json:"server,omitempty"`
	ServerPort   uint16   `json:"server_port,omitempty"`
	PublicKey    string   `json:"public_key"`
	PreSharedKey string   `json:"pre_shared_key,omitempty"`
	AllowedIPs   []string `json:"allowed_ips,omitempty"`
	Reserved     []uint8  `json:"reserved,omitempty"`
}

// HysteriaOutbound represents a Hysteria outbound
type HysteriaOutbound struct {
	Type            string        `json:"type"`
	Tag             string        `json:"tag"`
	Server          string        `json:"server"`
	ServerPort      uint16        `json:"server_port"`
	UpMbps          uint32        `json:"up_mbps,omitempty"`
	DownMbps        uint32        `json:"down_mbps,omitempty"`
	Obfs            string        `json:"obfs,omitempty"`
	Auth            string        `json:"auth,omitempty"`
	AuthString      string        `json:"auth_str,omitempty"`
	RecvWindowConn  uint64        `json:"recv_window_conn,omitempty"`
	RecvWindow      uint64        `json:"recv_window,omitempty"`
	DisableMTUDiscovery bool      `json:"disable_mtu_discovery,omitempty"`
	Network         string        `json:"network,omitempty"`
	TLS             *TLSOptions   `json:"tls,omitempty"`
	DialerOptions
}

// Hysteria2Outbound represents a Hysteria2 outbound
type Hysteria2Outbound struct {
	Type            string      `json:"type"`
	Tag             string      `json:"tag"`
	Server          string      `json:"server"`
	ServerPort      uint16      `json:"server_port"`
	UpMbps          uint32      `json:"up_mbps,omitempty"`
	DownMbps        uint32      `json:"down_mbps,omitempty"`
	Obfs            *Hysteria2ObfsOptions `json:"obfs,omitempty"`
	Password        string      `json:"password,omitempty"`
	Network         string      `json:"network,omitempty"`
	TLS             *TLSOptions `json:"tls,omitempty"`
	BrutalDebug     bool        `json:"brutal_debug,omitempty"`
	DialerOptions
}

// Hysteria2ObfsOptions contains Hysteria2 obfuscation options
type Hysteria2ObfsOptions struct {
	Type     string `json:"type"`
	Password string `json:"password"`
}

// TUICOutbound represents a TUIC outbound
type TUICOutbound struct {
	Type                string        `json:"type"`
	Tag                 string        `json:"tag"`
	Server              string        `json:"server"`
	ServerPort          uint16        `json:"server_port"`
	UUID                string        `json:"uuid"`
	Password            string        `json:"password,omitempty"`
	CongestionControl   string        `json:"congestion_control,omitempty"`
	UDPRelayMode        string        `json:"udp_relay_mode,omitempty"`
	UDPOverStream       bool          `json:"udp_over_stream,omitempty"`
	ZeroRTTHandshake    bool          `json:"zero_rtt_handshake,omitempty"`
	Heartbeat           uint32        `json:"heartbeat,omitempty"`
	Network             string        `json:"network,omitempty"`
	TLS                 *TLSOptions   `json:"tls,omitempty"`
	DialerOptions
}

// SSHOutbound represents an SSH tunnel outbound
type SSHOutbound struct {
	Type                string   `json:"type"`
	Tag                 string   `json:"tag"`
	Server              string   `json:"server"`
	ServerPort          uint16   `json:"server_port"`
	User                string   `json:"user"`
	Password            string   `json:"password,omitempty"`
	PrivateKey          string   `json:"private_key,omitempty"`
	PrivateKeyPath      string   `json:"private_key_path,omitempty"`
	PrivateKeyPassphrase string  `json:"private_key_passphrase,omitempty"`
	HostKey             []string `json:"host_key,omitempty"`
	HostKeyAlgorithms   []string `json:"host_key_algorithms,omitempty"`
	ClientVersion       string   `json:"client_version,omitempty"`
	DialerOptions
}

// TorOutbound represents a Tor network outbound
type TorOutbound struct {
	Type                string            `json:"type"`
	Tag                 string            `json:"tag"`
	ExecutablePath      string            `json:"executable_path,omitempty"`
	ExtraArgs           []string          `json:"extra_args,omitempty"`
	DataDirectory       string            `json:"data_directory,omitempty"`
	Torrc               map[string]string `json:"torrc,omitempty"`
	DialerOptions
}

// SelectorOutbound represents a manual selection group outbound
type SelectorOutbound struct {
	Type                      string   `json:"type"`
	Tag                       string   `json:"tag"`
	Outbounds                 []string `json:"outbounds"`
	Default                   string   `json:"default,omitempty"`
	InterruptExistConnections bool     `json:"interrupt_exist_connections,omitempty"`
}

// URLTestOutbound represents an automatic selection group outbound
type URLTestOutbound struct {
	Type                      string   `json:"type"`
	Tag                       string   `json:"tag"`
	Outbounds                 []string `json:"outbounds"`
	URL                       string   `json:"url,omitempty"`
	Interval                  uint32   `json:"interval,omitempty"`
	Tolerance                 uint32   `json:"tolerance,omitempty"`
	IdleTimeout               uint32   `json:"idle_timeout,omitempty"`
	InterruptExistConnections bool     `json:"interrupt_exist_connections,omitempty"`
}
