// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/route/rule
// Commit: 877e7a8
// Generated at: 2025-11-23T20:44:59Z

package types

type OutboundOptionsRegistry struct {
}

type DialerOptionsWrapper struct {
}

type DialerOptions struct {
	Detour              string       `json:"detour,omitempty"`
	BindInterface       string       `json:"bind_interface,omitempty"`
	Inet4BindAddress    *string      `json:"inet4_bind_address,omitempty"`
	Inet6BindAddress    *string      `json:"inet6_bind_address,omitempty"`
	ProtectPath         string       `json:"protect_path,omitempty"`
	RoutingMark         uint32       `json:"routing_mark,omitempty"`
	ReuseAddr           bool         `json:"reuse_addr,omitempty"`
	NetNs               string       `json:"netns,omitempty"`
	ConnectTimeout      uint32       `json:"connect_timeout,omitempty"`
	TCPFastOpen         bool         `json:"tcp_fast_open,omitempty"`
	TCPMultiPath        bool         `json:"tcp_multi_path,omitempty"`
	UDPFragment         *bool        `json:"udp_fragment,omitempty"`
	DomainResolver      *interface{} `json:"domain_resolver,omitempty"`
	NetworkStrategy     *string      `json:"network_strategy,omitempty"`
	NetworkType         []string     `json:"network_type,omitempty"`
	FallbackNetworkType []string     `json:"fallback_network_type,omitempty"`
	FallbackDelay       uint32       `json:"fallback_delay,omitempty"`
	// Deprecated: migrated to domain resolver
	DomainStrategy string `json:"domain_strategy,omitempty"`
}

type ServerOptionsWrapper struct {
}

type ServerOptions struct {
	Server     string `json:"server"`
	ServerPort uint16 `json:"server_port"`
}
