// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/route/rule
// Commit: 877e7a8
// Generated at: 2025-11-23T20:44:59Z

package types

type RouteOptions struct {
	GeoIP                      *GeoIPOptions   `json:"geoip,omitempty"`
	Geosite                    *GeositeOptions `json:"geosite,omitempty"`
	Rules                      []interface{}   `json:"rules,omitempty"`
	RuleSet                    []interface{}   `json:"rule_set,omitempty"`
	Final                      string          `json:"final,omitempty"`
	FindProcess                bool            `json:"find_process,omitempty"`
	AutoDetectInterface        bool            `json:"auto_detect_interface,omitempty"`
	OverrideAndroidVPN         bool            `json:"override_android_vpn,omitempty"`
	DefaultInterface           string          `json:"default_interface,omitempty"`
	DefaultMark                uint32          `json:"default_mark,omitempty"`
	DefaultDomainResolver      *interface{}    `json:"default_domain_resolver,omitempty"`
	DefaultNetworkStrategy     *string         `json:"default_network_strategy,omitempty"`
	DefaultNetworkType         []string        `json:"default_network_type,omitempty"`
	DefaultFallbackNetworkType []string        `json:"default_fallback_network_type,omitempty"`
	DefaultFallbackDelay       uint32          `json:"default_fallback_delay,omitempty"`
}

type GeoIPOptions struct {
	Path           string `json:"path,omitempty"`
	DownloadURL    string `json:"download_url,omitempty"`
	DownloadDetour string `json:"download_detour,omitempty"`
}

type GeositeOptions struct {
	Path           string `json:"path,omitempty"`
	DownloadURL    string `json:"download_url,omitempty"`
	DownloadDetour string `json:"download_detour,omitempty"`
}
