// Code generated by singbox-web-config generator. DO NOT EDIT.
// Source: https://github.com/SagerNet/sing-box/tree/dev-next/route/rule
// Commit: 877e7a8
// Generated at: 2025-11-23T20:44:59Z

package types

type RawDefaultDNSRule struct {
	// Action field (required in sing-box 1.11.0+)
	// Manually added for web interface compatibility
	Action string `json:"action,omitempty"`

	// Action-specific fields
	// For "route" action (DNS server routing)
	Server       string  `json:"server,omitempty"`
	DNSStrategy  string  `json:"strategy,omitempty"`
	DisableCache bool    `json:"disable_cache,omitempty"`
	RewriteTTL   *uint32 `json:"rewrite_ttl,omitempty"`
	ClientSubnet *string `json:"client_subnet,omitempty"`

	// Rule matching fields
	Inbound                  []string                `json:"inbound,omitempty"`
	IPVersion                int                     `json:"ip_version,omitempty"`
	QueryType                []string                `json:"query_type,omitempty"`
	Network                  []string                `json:"network,omitempty"`
	AuthUser                 []string                `json:"auth_user,omitempty"`
	Protocol                 []string                `json:"protocol,omitempty"`
	Domain                   []string                `json:"domain,omitempty"`
	DomainSuffix             []string                `json:"domain_suffix,omitempty"`
	DomainKeyword            []string                `json:"domain_keyword,omitempty"`
	DomainRegex              []string                `json:"domain_regex,omitempty"`
	Geosite                  []string                `json:"geosite,omitempty"`
	SourceGeoIP              []string                `json:"source_geoip,omitempty"`
	GeoIP                    []string                `json:"geoip,omitempty"`
	IPCIDR                   []string                `json:"ip_cidr,omitempty"`
	IPIsPrivate              bool                    `json:"ip_is_private,omitempty"`
	IPAcceptAny              bool                    `json:"ip_accept_any,omitempty"`
	SourceIPCIDR             []string                `json:"source_ip_cidr,omitempty"`
	SourceIPIsPrivate        bool                    `json:"source_ip_is_private,omitempty"`
	SourcePort               []uint16                `json:"source_port,omitempty"`
	SourcePortRange          []string                `json:"source_port_range,omitempty"`
	Port                     []uint16                `json:"port,omitempty"`
	PortRange                []string                `json:"port_range,omitempty"`
	ProcessName              []string                `json:"process_name,omitempty"`
	ProcessPath              []string                `json:"process_path,omitempty"`
	ProcessPathRegex         []string                `json:"process_path_regex,omitempty"`
	PackageName              []string                `json:"package_name,omitempty"`
	User                     []string                `json:"user,omitempty"`
	UserID                   []int32                 `json:"user_id,omitempty"`
	Outbound                 []string                `json:"outbound,omitempty"`
	ClashMode                string                  `json:"clash_mode,omitempty"`
	NetworkType              []string                `json:"network_type,omitempty"`
	NetworkIsExpensive       bool                    `json:"network_is_expensive,omitempty"`
	NetworkIsConstrained     bool                    `json:"network_is_constrained,omitempty"`
	WIFISSID                 []string                `json:"wifi_ssid,omitempty"`
	WIFIBSSID                []string                `json:"wifi_bssid,omitempty"`
	InterfaceAddress         *map[string]interface{} `json:"interface_address,omitempty"`
	NetworkInterfaceAddress  *map[string]interface{} `json:"network_interface_address,omitempty"`
	DefaultInterfaceAddress  []*string               `json:"default_interface_address,omitempty"`
	RuleSet                  []string                `json:"rule_set,omitempty"`
	RuleSetIPCIDRMatchSource bool                    `json:"rule_set_ip_cidr_match_source,omitempty"`
	RuleSetIPCIDRAcceptEmpty bool                    `json:"rule_set_ip_cidr_accept_empty,omitempty"`
	Invert                   bool                    `json:"invert,omitempty"`
	// Deprecated: renamed to rule_set_ip_cidr_match_source
	Deprecated_RulesetIPCIDRMatchSource bool `json:"rule_set_ipcidr_match_source,omitempty"`
}

type DefaultDNSRule struct {
}

type RawLogicalDNSRule struct {
	Mode   string        `json:"mode"`
	Rules  []interface{} `json:"rules,omitempty"`
	Invert bool          `json:"invert,omitempty"`
}

type LogicalDNSRule struct {
}

type LocalRuleSet struct {
	Path string `json:"path,omitempty"`
}

type RemoteRuleSet struct {
	URL            string `json:"url"`
	DownloadDetour string `json:"download_detour,omitempty"`
	UpdateInterval uint32 `json:"update_interval,omitempty"`
}

type DefaultHeadlessRule struct {
	QueryType               []string                `json:"query_type,omitempty"`
	Network                 []string                `json:"network,omitempty"`
	Domain                  []string                `json:"domain,omitempty"`
	DomainSuffix            []string                `json:"domain_suffix,omitempty"`
	DomainKeyword           []string                `json:"domain_keyword,omitempty"`
	DomainRegex             []string                `json:"domain_regex,omitempty"`
	SourceIPCIDR            []string                `json:"source_ip_cidr,omitempty"`
	IPCIDR                  []string                `json:"ip_cidr,omitempty"`
	SourcePort              []uint16                `json:"source_port,omitempty"`
	SourcePortRange         []string                `json:"source_port_range,omitempty"`
	Port                    []uint16                `json:"port,omitempty"`
	PortRange               []string                `json:"port_range,omitempty"`
	ProcessName             []string                `json:"process_name,omitempty"`
	ProcessPath             []string                `json:"process_path,omitempty"`
	ProcessPathRegex        []string                `json:"process_path_regex,omitempty"`
	PackageName             []string                `json:"package_name,omitempty"`
	NetworkType             []string                `json:"network_type,omitempty"`
	NetworkIsExpensive      bool                    `json:"network_is_expensive,omitempty"`
	NetworkIsConstrained    bool                    `json:"network_is_constrained,omitempty"`
	WIFISSID                []string                `json:"wifi_ssid,omitempty"`
	WIFIBSSID               []string                `json:"wifi_bssid,omitempty"`
	NetworkInterfaceAddress *map[string]interface{} `json:"network_interface_address,omitempty"`
	DefaultInterfaceAddress []*string               `json:"default_interface_address,omitempty"`
	Invert                  bool                    `json:"invert,omitempty"`
}

type LogicalHeadlessRule struct {
	Mode   string        `json:"mode"`
	Rules  []interface{} `json:"rules,omitempty"`
	Invert bool          `json:"invert,omitempty"`
}

type PlainRuleSet struct {
	Rules []interface{} `json:"rules,omitempty"`
}

type RawDefaultRule struct {
	// Action field (required in sing-box 1.11.0+)
	// Manually added for web interface compatibility
	Action string `json:"action,omitempty"`

	// Action-specific fields
	// For "route" action
	Outbound string `json:"outbound,omitempty"`

	// For "sniff" action
	Sniffer      []string `json:"sniffer,omitempty"`
	SniffTimeout uint32   `json:"timeout,omitempty"`

	// For "resolve" action
	Server       string  `json:"server,omitempty"`
	Strategy     string  `json:"strategy,omitempty"`
	DisableCache bool    `json:"disable_cache,omitempty"`
	RewriteTTL   *uint32 `json:"rewrite_ttl,omitempty"`
	ClientSubnet *string `json:"client_subnet,omitempty"`

	// For "reject" action
	Method string `json:"method,omitempty"`
	NoDrop bool   `json:"no_drop,omitempty"`

	// For "route-options" action
	OverrideAddress           string  `json:"override_address,omitempty"`
	OverridePort              uint16  `json:"override_port,omitempty"`
	NetworkStrategy           *string `json:"network_strategy,omitempty"`
	FallbackDelay             uint32  `json:"fallback_delay,omitempty"`
	UDPDisableDomainUnmapping bool    `json:"udp_disable_domain_unmapping,omitempty"`
	UDPConnect                bool    `json:"udp_connect,omitempty"`
	UDPTimeout                uint32  `json:"udp_timeout,omitempty"`
	TLSFragment               bool    `json:"tls_fragment,omitempty"`
	TLSFragmentFallbackDelay  uint32  `json:"tls_fragment_fallback_delay,omitempty"`
	TLSRecordFragment         bool    `json:"tls_record_fragment,omitempty"`

	// Rule matching fields
	Inbound                  []string                `json:"inbound,omitempty"`
	IPVersion                int                     `json:"ip_version,omitempty"`
	Network                  []string                `json:"network,omitempty"`
	AuthUser                 []string                `json:"auth_user,omitempty"`
	Protocol                 []string                `json:"protocol,omitempty"`
	Client                   []string                `json:"client,omitempty"`
	Domain                   []string                `json:"domain,omitempty"`
	DomainSuffix             []string                `json:"domain_suffix,omitempty"`
	DomainKeyword            []string                `json:"domain_keyword,omitempty"`
	DomainRegex              []string                `json:"domain_regex,omitempty"`
	Geosite                  []string                `json:"geosite,omitempty"`
	SourceGeoIP              []string                `json:"source_geoip,omitempty"`
	GeoIP                    []string                `json:"geoip,omitempty"`
	SourceIPCIDR             []string                `json:"source_ip_cidr,omitempty"`
	SourceIPIsPrivate        bool                    `json:"source_ip_is_private,omitempty"`
	IPCIDR                   []string                `json:"ip_cidr,omitempty"`
	IPIsPrivate              bool                    `json:"ip_is_private,omitempty"`
	SourcePort               []uint16                `json:"source_port,omitempty"`
	SourcePortRange          []string                `json:"source_port_range,omitempty"`
	Port                     []uint16                `json:"port,omitempty"`
	PortRange                []string                `json:"port_range,omitempty"`
	ProcessName              []string                `json:"process_name,omitempty"`
	ProcessPath              []string                `json:"process_path,omitempty"`
	ProcessPathRegex         []string                `json:"process_path_regex,omitempty"`
	PackageName              []string                `json:"package_name,omitempty"`
	User                     []string                `json:"user,omitempty"`
	UserID                   []int32                 `json:"user_id,omitempty"`
	ClashMode                string                  `json:"clash_mode,omitempty"`
	NetworkType              []string                `json:"network_type,omitempty"`
	NetworkIsExpensive       bool                    `json:"network_is_expensive,omitempty"`
	NetworkIsConstrained     bool                    `json:"network_is_constrained,omitempty"`
	WIFISSID                 []string                `json:"wifi_ssid,omitempty"`
	WIFIBSSID                []string                `json:"wifi_bssid,omitempty"`
	InterfaceAddress         *map[string]interface{} `json:"interface_address,omitempty"`
	NetworkInterfaceAddress  *map[string]interface{} `json:"network_interface_address,omitempty"`
	DefaultInterfaceAddress  []*string               `json:"default_interface_address,omitempty"`
	PreferredBy              []string                `json:"preferred_by,omitempty"`
	RuleSet                  []string                `json:"rule_set,omitempty"`
	RuleSetIPCIDRMatchSource bool                    `json:"rule_set_ip_cidr_match_source,omitempty"`
	Invert                   bool                    `json:"invert,omitempty"`
	// Deprecated: renamed to rule_set_ip_cidr_match_source
	Deprecated_RulesetIPCIDRMatchSource bool `json:"rule_set_ipcidr_match_source,omitempty"`
}

type DefaultRule struct {
}

type RawLogicalRule struct {
	Mode   string        `json:"mode"`
	Rules  []interface{} `json:"rules,omitempty"`
	Invert bool          `json:"invert,omitempty"`
}

type LogicalRule struct {
}

type RouteActionOptions struct {
	Outbound string `json:"outbound,omitempty"`
}

type RawRouteOptionsActionOptions struct {
	OverrideAddress           string  `json:"override_address,omitempty"`
	OverridePort              uint16  `json:"override_port,omitempty"`
	NetworkStrategy           *string `json:"network_strategy,omitempty"`
	FallbackDelay             uint32  `json:"fallback_delay,omitempty"`
	UDPDisableDomainUnmapping bool    `json:"udp_disable_domain_unmapping,omitempty"`
	UDPConnect                bool    `json:"udp_connect,omitempty"`
	UDPTimeout                uint32  `json:"udp_timeout,omitempty"`
	TLSFragment               bool    `json:"tls_fragment,omitempty"`
	TLSFragmentFallbackDelay  uint32  `json:"tls_fragment_fallback_delay,omitempty"`
	TLSRecordFragment         bool    `json:"tls_record_fragment,omitempty"`
}

type DNSRouteActionOptions struct {
	Server       string  `json:"server,omitempty"`
	Strategy     string  `json:"strategy,omitempty"`
	DisableCache bool    `json:"disable_cache,omitempty"`
	RewriteTTL   *uint32 `json:"rewrite_ttl,omitempty"`
	ClientSubnet *string `json:"client_subnet,omitempty"`
}

type RouteActionSniff struct {
	Sniffer []string `json:"sniffer,omitempty"`
	Timeout uint32   `json:"timeout,omitempty"`
}

type RouteActionResolve struct {
	Server       string  `json:"server,omitempty"`
	Strategy     string  `json:"strategy,omitempty"`
	DisableCache bool    `json:"disable_cache,omitempty"`
	RewriteTTL   *uint32 `json:"rewrite_ttl,omitempty"`
	ClientSubnet *string `json:"client_subnet,omitempty"`
}

type DNSRouteActionPredefined struct {
	Rcode  *uint16       `json:"rcode,omitempty"`
	Answer []interface{} `json:"answer,omitempty"`
	Ns     []interface{} `json:"ns,omitempty"`
	Extra  []interface{} `json:"extra,omitempty"`
}
